### ISSUE TITLE
External World shows over iva

### ISSUE THREAD

**Issue by daintysage** [linuxgurugamer/DockingCam#16]
hard to explain but this picture sows the problem and I have isolated the issue onto an almost completely vanilla game
[https://drive.google.com/file/d/1N0oYjB3wIjHgXU24jNH8-Qi9WVlmHCvu/view?usp=sharing](url)

**Comment by linuxgurugamer** [comment]
Would be nice if I had access
Also, please provide a log file of the game in which it happened.

**Comment by wile1411** [comment]
I just tested it as well and can confirm - looking into it now

**Comment by wile1411** [comment]
I had one other solution that's a complete kludge and I know it works. It would be ideal to have someone to test on a mac or linux to confirm there are no other side effect. I'll send you a PR in case you want to test.

**Comment by wile1411** [comment]
Added PR #17 for testing

**Comment by linuxgurugamer** [comment]
Ok, I'll take a look later.
thanks for the quick response

**Comment by linuxgurugamer** [comment]
> hard to explain but this picture sows the problem and I have isolated the issue onto an almost completely vanilla game
> [https://drive.google.com/file/d/1N0oYjB3wIjHgXU24jNH8-Qi9WVlmHCvu/view?usp=sharing](url)

Please try this beta:  https://www.dropbox.com/s/8hunr0g4sfasmo5/DockingCamKURS-1.3.7.8.zip?dl=0
