### ISSUE TITLE
No camera feed on KSP 1.7 

### ISSUE THREAD

**Issue by XanatosX** [linuxgurugamer/DockingCam#2]
I do play in career mode  in KSP but in the menu of the camera item is no option to turn it in. The same problems seems to appear on any docking port. Not sure if this is a result of installing the mode after starting the save or if this is not working in career mode at all. 

I did try to install the camera which you get pretty early in the tech tree but there is only an option to rename the part no option to activate the camera.

Do I need to configure something?

**Comment by XanatosX** [comment]
So I did test it in the sandbox mode as well and the problem is present there too. 

I was installing this via CKAN

**Comment by linuxgurugamer** [comment]
Install the ToolbarController and the ClickThrough Blocker.  Looks like those are missing as dependencies in CKAN.  Please let me know if this solves the problem

**Comment by linuxgurugamer** [comment]
If I don't hear anything by Sunday, I'll assume the problem has been solved

**Comment by XanatosX** [comment]
I wasn't able to play since I wrote down this issue.

But I did a quick test and after installing the required dependencies the mod is working just fine.

Thank you for helping me out :)
