### ISSUE TITLE
Not work  in KSP 1.11.2

### ISSUE THREAD

**Issue by looogin** [linuxgurugamer/DockingCam#24]
Mod not work  in KSP 1.11.2. Parts from mod not working.

**Comment by linuxgurugamer** [comment]
Rather uninformative.

Please post in the forum with this, you most likely have missing dependencies or a bad install.
https://forum.kerbalspaceprogram.com/index.php?/topic/184038-19x-110x-docking-camera-kurs-style-re-adopted-fixed-in-19/
