### ISSUE TITLE
Crash on switching to vessel, from DockingCameraModule?

### ISSUE THREAD

**Issue by Rodg88** [linuxgurugamer/DockingCam#27]
Switched to a station with a lot of docking ports, and just got a CTD. The stack trace mentions OLDD_camera.Modules.DockingCameraModule.

Player Log:
https://drive.google.com/file/d/1-DWYQdQO6SFpuINX7tTRrMhXsczNcyg_/view?usp=sharing

Unusually, it said it created a crash log in temp/squad/kerbal space program/crashes, but the folder it made was empty.

**Comment by linuxgurugamer** [comment]
The error is deep inside Unity, this has nothing to do with the mod.

Try it again and see if the same thing happens, let me know if it does
