### ISSUE TITLE
Linux Shaders

### ISSUE THREAD

**Issue by ivoriesablaze** [linuxgurugamer/DockingCam#7]
In Linux, the camera itself works, but does not show a visual in game. I'm able to confirm it works as I have been able to take screenshots from it. As per our conversation, this is to remind you to work on the Linux shaders. 

Thanks for all you do, Linux!

**Comment by linuxgurugamer** [comment]
Try this file.  Unzip contents into into (kspDir)/GameData/DockingCamKURS/Resources
It replaces the file DockingCam.ksp

I've provided both a link to a dropbox download and included it here

Please let me know ASAP how it goes
https://www.dropbox.com/s/8i0b1ommu8mwrpk/DockingCam-Linux.zip?dl=0
[DockingCam-Linux.zip](https://github.com/linuxgurugamer/DockingCam/files/3814450/DockingCam-Linux.zip)

**Comment by linuxgurugamer** [comment]
Please let me know how it goes, I'm holding off on the 1.8 update for this mod until you get back to me

**Comment by ivoriesablaze** [comment]
The issue is still persisting as per these [screenshots](https://imgur.com/a/8N6WU2t). This is the current list of mods I have

```
KSP: 1.8.1 (Unix) - Unity: 2019.2.2f1 - OS: Linux 5.3 Ubuntu 19.10 64bit
ClickThroughBlocker - 0.1.9.3
Toolbar - 1.8.0.5
ToolbarControl - 0.1.9.4
ABCors - 0.5.1.2
Chatterer - 0.9.98.2686
Community Category Kit - 4.1
DatedQuickSaves - 1.2.4.2
DecouplerShroud - 0.7.2
DestructionEffects - 1.11
DockingCamKURS - 1.3.6.3
DraftTwitchViewers - 2.7.0.2
EditorExtensionsRedux - 3.4.0.2
Engine Lighting Relit - 1.6.2.2
Environmental Visual Enhancements - 1.8.0.2
KSP-AVC Plugin - 1.4.0.2
KSPLogger - 0.6
Kerbal Engineer Redux - 1.1.7.1
LaunchCountDown - 1.8.0.2686
MagiCore - 1.3.2.3
NavHud - 1.4.0.2
Parking Brake - 0.2
Precise Maneuver - 2.4.4
RealPlume - Stock - 2.0.1
ShipSaveSplicer - 1.1.5.2
Kerbal Alarm Clock - 3.11
[x] Science! - 5.22
```

I'll test it without mods later and keep you posted.

**Comment by linuxgurugamer** [comment]
Oh, you are running 1.8.1.
then you will have other issues.
I'll push the 1.8.1 update this evening, please wait for that.
For this specific problem, you don't need to remove other mods

**Comment by ivoriesablaze** [comment]
Ah, okay. Did you need me to test it on the 1.7 version anyway?

**Comment by linuxgurugamer** [comment]
if you can.

**Comment by linuxgurugamer** [comment]
I have set up a Linux install to test the shaders on Linux

**Comment by ivoriesablaze** [comment]
Okay, I went ahead and tried 1.7.3 anyway and got the same results, though the pop up box now has no options in it. I'll test out the 1.8.1 release when you drop it later.

For all I know, it could just be my config at this point.

**Comment by linuxgurugamer** [comment]
I don't think it's your config.  I've created a local Linux install, hope to be able to work on this soon.
